<h1>Questions</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?php if ($this->questions): ?>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Category</th>
                    <th><span class="pull-right">Action</span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->questions as $question): ?>
                <tr>
                    <td><?php echo $question->name; ?></td>
                    <td><?php echo $question->category->name; ?></td>
                    <td>
                        <div class="btn-group pull-right" role="group">
                            <a href="<?php echo $this->url(array('controller' => 'question', 'action' => 'edit', 'id' => $question->id), null, true); ?>" class="btn btn-default btn-xs">Edit</a>
                            <a href="<?php echo $this->url(array('controller' => 'question', 'action' => 'delete', 'id' => $question->id), null, true); ?>" class="btn btn-default btn-xs">Delete</a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>

            </tbody>
        </table>
        <?php endif; ?>
        <a href="<?php echo $this->url(array('controller' => 'question', 'action' => 'edit'), null, true); ?>" class="btn btn-default btn-sm pull-right">Add Question</a>
    </div>
</div>



