<h1>Questions</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?php if ($this->questions): ?>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th><span class="pull-right">Action</span></th>
                </tr>
            </thead>
            <tbody>


            </tbody>
        </table>
        <?php endif; ?>
        <a href="<?php echo $this->url(array('controller' => 'question', 'action' => 'edit'), null, true); ?>" class="btn btn-default btn-sm pull-right">Add Question</a>
    </div>
</div>