<?php
$auth = Zend_Auth::getInstance();
$acl = ACL_Model_Authentication::getInstance();
?>
<!-- Static navbar -->
<div class="row">
<div class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <!--<span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>-->
                <i class="fa fa-bars"></i>
            </button>
        <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'),null ,true); ?>">Title</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <?php if ($acl->authoriseResource('unauthenticated')): ?>
                <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true);?>">Guest</a></li>
                <?php endif; ?>
                
                <?php if($acl->authoriseResource('base_user')): ?>
                <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true);?>">User</a></li>
                <?php endif; ?>
                
                <?php if($acl->authoriseResource('admin')): ?>
                <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true);?>">Admin</a></li>
                <?php endif; ?>
                
                <?php if($acl->authoriseResource('super_admin')): ?>
                <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true);?>">Super</a></li>
                <?php endif; ?>
            </ul>

            <!-- Right Links -->
            <ul class="nav navbar-nav navbar-right">
                <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                <li><a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout'),null ,true); ?>">Log out <i class="fa fa-sign-out fa-fw"></i></a></li>
                <?php else: ?>
                <li><a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login'),null ,true); ?>">Log in <i class="fa fa-sign-in fa-fw"></i></a></li>
                <?php endif;?>
            </ul>

            <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <!-- Search -->
            <div class="col-xs-12 col-sm-4 col-md-4">
                <form class="navbar-form" role="search" id="search-form" name="search-form" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'search'),null,true); ?>" method="post">
                    <div class="input-group">
                        <input type="text" class="form-control input-sm" placeholder="Search" id="query" name="keyword" autocomplete="off" value="<?php echo $this->keyword; ?>">
                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-primary btn-sm"><span class="fa fa-search"></span></button>
                        </div>
                    </div>
                </form>
            </div>
            <?php endif; ?>

        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</div>
</div>

