<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Title');
    echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()
                ->appendStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css')
                ->appendStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
                ->appendStylesheet('//netdna.bootstrapcdn.com/bootswatch/3.3.1/simplex/bootstrap.min.css'); ?>
        <meta name="viewport" content="width=312; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
    </head>
    <body>
        <div class="container">
            <?php echo $this->partial('partials/navigation.phtml', array('keyword' => $this->keyword)); ?>
            <?php echo $this->title ? '<div class="page-header"><h2>' . $this->title . ' <small>' . $this->subtitle . '</small></h2></div>' : ''; ?>
        	<?php echo $this->flash(); ?>
            <?php echo $this->layout()->content; ?>
            <footer>
                <?php echo $this->partial('partials/footer.phtml', array('mode' => $this->mode)); ?>
            </footer>
        </div>
        <?php echo $this->headScript()
                ->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')
                ->appendFile('//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js'); ?>
    </body>
</html>
